In [2]:
import sys
from operator import index
from pathlib import Path
sys.path.append(str(Path("..").resolve()))

import pandas as pd
from src.features.build_features import split_birth_date, zodiac_sign

In [3]:
data = pd.read_csv('../data/raw/fifa_players.csv')

### Selecting Target Features for Market Value and Wage Prediction

In [15]:
# Extract the target feature for player market value.
# This feature shows the estimated value of each football player in euros.
value_euro_target_feature = data['value_euro']

# Extract the target feature for player wage.
# This feature shows the player's wage in euros.
wage_euro_target_feature = data['wage_euro']

# value_euro_target_feature.to_csv('value_euro_target_feature.csv', index=False)
# wage_euro_target_feature.to_csv('wage_euro_target_feature.csv', index=False)

### Splitting the Birth Date into Separate Date Components

In [4]:
data = split_birth_date(data)
data

,name,full_name,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,value_euro,...,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle,month,day,year
0,L. Messi,Lionel Andrés Messi Cuccittini,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,110500000.0,...,94,94,75,96,33,28,26,6,24,1987
1,C. Eriksen,Christian Dannemann Eriksen,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,69500000.0,...,84,91,67,88,59,57,22,2,14,1992
2,P. Pogba,Paul Pogba,25,190.50,83.9,"CM,CAM",France,88,91,73000000.0,...,82,88,82,87,63,67,67,3,15,1993
3,L. Insigne,Lorenzo Insigne,27,162.56,59.0,"LW,ST",Italy,88,88,62000000.0,...,83,87,61,83,51,24,22,6,4,1991
4,K. Koulibaly,Kalidou Koulibaly,27,187.96,88.9,CB,Senegal,88,91,60000000.0,...,24,49,33,80,91,88,87,6,20,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,R. McKenzie,Rory McKenzie,25,175.26,74.8,"RM,CAM,CM",Scotland,67,70,975000.0,...,60,64,63,56,40,20,18,10,7,1993
17950,M. Sipľak,Michal Sipľak,23,182.88,79.8,LB,Slovakia,59,67,190000.0,...,42,39,32,52,53,64,60,2,2,1996
17951,J. Bekkema,Jan Bekkema,22,185.42,89.8,GK,Netherlands,59,67,170000.0,...,5,25,16,47,9,12,13,4,9,1996
17952,A. Al Yami,Abdulrahman Al Yami,21,175.26,64.9,"ST,LM",Saudi Arabia,59,71,280000.0,...,54,52,50,53,16,18,17,6,19,1997
17953,Júnior Brumado,José Francisco dos Santos Júnior,19,190.50,79.8,ST,Brazil,59,75,325000.0,...,53,49,52,45,23,31,21,5,15,1999

### Zodiac Signs and Football Player Performance

In this section, we will examine the zodiac signs of the football players in the dataset. The goal is to explore whether there are any visible patterns or relationships between a player's zodiac sign and their performance indicators, as well as possible connections with other features.

There is a lot of popular information online suggesting that people born under the same zodiac sign may share certain personality traits. Although astrology is not considered a scientific method for evaluating athletic ability, this feature can still be explored from a data analysis perspective. The purpose here is not to prove causation, but to check whether any interesting patterns appear in the available data.

In [5]:
data['zodiac'] = data.apply(
    lambda row: zodiac_sign(row['day'], row['month']),
    axis=1
)
data

,name,full_name,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,value_euro,...,vision,penalties,composure,marking,standing_tackle,sliding_tackle,month,day,year,zodiac
0,L. Messi,Lionel Andrés Messi Cuccittini,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,110500000.0,...,94,75,96,33,28,26,6,24,1987,Cancer
1,C. Eriksen,Christian Dannemann Eriksen,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,69500000.0,...,91,67,88,59,57,22,2,14,1992,Aquarius
2,P. Pogba,Paul Pogba,25,190.50,83.9,"CM,CAM",France,88,91,73000000.0,...,88,82,87,63,67,67,3,15,1993,Pisces
3,L. Insigne,Lorenzo Insigne,27,162.56,59.0,"LW,ST",Italy,88,88,62000000.0,...,87,61,83,51,24,22,6,4,1991,Gemini
4,K. Koulibaly,Kalidou Koulibaly,27,187.96,88.9,CB,Senegal,88,91,60000000.0,...,49,33,80,91,88,87,6,20,1991,Gemini
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,R. McKenzie,Rory McKenzie,25,175.26,74.8,"RM,CAM,CM",Scotland,67,70,975000.0,...,64,63,56,40,20,18,10,7,1993,Libra
17950,M. Sipľak,Michal Sipľak,23,182.88,79.8,LB,Slovakia,59,67,190000.0,...,39,32,52,53,64,60,2,2,1996,Aquarius
17951,J. Bekkema,Jan Bekkema,22,185.42,89.8,GK,Netherlands,59,67,170000.0,...,25,16,47,9,12,13,4,9,1996,Aries
17952,A. Al Yami,Abdulrahman Al Yami,21,175.26,64.9,"ST,LM",Saudi Arabia,59,71,280000.0,...,52,50,53,16,18,17,6,19,1997,Gemini
17953,Júnior Brumado,José Francisco dos Santos Júnior,19,190.50,79.8,ST,Brazil,59,75,325000.0,...,49,52,45,23,31,21,5,15,1999,Taurus